### PR TITLE
feat - added my name to the repo

### PR DESCRIPTION
**Pull request by muskan308**

### CODE REVIEW

**Comment by Mohasin-Haque** [comment]
@muskan308 This PR has some conflicts. Please resolve it so that I can merge it. Please feel free to ask for help if you can not resolve it.

**Comment by muskan308** [comment]
I am unable to figure out how to resolve the conflict. Please help me.

**Comment by Mohasin-Haque** [comment]
Congratulations @muskan308 You made your contribution.. 😊 Keep it up. Hope to work with you again.

**Comment by muskan308** [comment]
Thank you for the support

**Pull request merged**
